# Generated by Django 4.0.5 on 2022-06-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
