# Generated by Django 4.0.5 on 2022-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_variationmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel')),
                ('descreption', models.TextField()),
                ('offers', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
