# Generated by Django 4.0.5 on 2022-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
