# Generated by Django 4.0.5 on 2022-07-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_bestsellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', unique=True),
        ),
    ]
