# Generated by Django 4.0.5 on 2022-07-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_bestsellers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellers',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
