# Generated by Django 4.0.5 on 2022-07-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_rename_descprition_category_description_and_more'),
        ('store', '0013_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=225, upload_to='products'),
        ),
    ]
