# Generated by Django 4.0.5 on 2022-07-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_rename_descprition_category_description_and_more'),
        ('store', '0014_alter_productgallery_options_carousel_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='carousel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
