# Generated by Django 4.0.5 on 2022-06-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('descprition', models.TextField(blank=True)),
                ('Main_cat_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('descprition', models.TextField(blank=True)),
                ('Main_cat_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('descprition', models.TextField(blank=True)),
                ('Main_cat_image', models.ImageField(blank=True, upload_to='photos/category')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.maincategory'),
        ),
    ]
