# Generated by Django 4.0.5 on 2022-06-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Maincategory', 'verbose_name_plural': 'Maincategories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
