# Generated by Django 4.0.5 on 2022-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='brand',
        ),
    ]
