# Generated by Django 4.0.5 on 2022-06-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_subcategory_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='slug',
            new_name='main_category_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='sub_category_slug',
        ),
    ]
