# Generated by Django 4.0.5 on 2022-06-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_slug_category_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_category_slug',
            new_name='slug',
        ),
    ]
