# Generated by Django 4.0.5 on 2022-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_main_category_slug_maincategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='main_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
