# Generated by Django 4.0.5 on 2022-06-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_maincategory_main_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category_slug',
            new_name='slug',
        ),
    ]
