# Generated by Django 4.0.5 on 2022-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_rename_category_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
