# Generated by Django 4.0.5 on 2022-07-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Main_cat_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='Main_cat_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Main_cat_image',
            new_name='image',
        ),
    ]
