# Generated by Django 4.0.5 on 2022-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_rename_main_cat_image_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='descprition',
            new_name='description',
        ),
    ]
