# Generated by Django 4.0.5 on 2022-07-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_rename_descprition_maincategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descprition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='descprition',
            new_name='description',
        ),
    ]
